---
title: "Beta Diversity"
author: "Jessica Wang"
date: "2025-11-24"
output: html_document
---

## Load Libraries
```{r Loading Libraries }
library(phyloseq)
library(vegan)
library(dplyr)
library(ggplot2)
library(ANCOMBC)
library(tidyverse)

ps <- readRDS("../Datasets/Phyloseq Objects/ps_alldoses.rds")

ps1 <- readRDS("../Datasets/Phyloseq Objects/ps_dose1.rds")

ps2 <- readRDS("../Datasets/Phyloseq Objects/ps_dose4.rds")

```

## Compute Weighted Unifrac for 1-dose
```{r Computation for Weighted Unifrac 1 dose}
set.seed(123)
wu_dist <- distance(ps1, method = "unifrac", weighted = TRUE)

ord_nmds <- ordinate(ps1, method = "NMDS", distance = wu_dist, trymax = 100)

p1_nmds <- plot_ordination(ps1, ord_nmds, color = "Response",
                          shape = "Vaccination.status") +
  geom_point(size = 3, alpha = 0.9) +
  theme_classic() +
  labs(
    title = "Weighted UniFrac NMDS",
    color = "Humoral response",
    shape = "Vaccination status")

p1_nmds
```

## Compute Weighted Unifrac for 4-dose
```{r Computation of Weighted Unifrac for 4 dose}
set.seed(123)
wu_dist2 <- distance(ps2, method = "unifrac", weighted = TRUE)

ord_nmds2 <- ordinate(ps2, method = "NMDS", distance = wu_dist2, trymax = 100)

p2_nmds <- plot_ordination(ps2, ord_nmds2, color = "Response",
                          shape = "Vaccination.status") +
  geom_point(size = 3, alpha = 0.9) +
  theme_classic() +
  labs(
    title = "Weighted UniFrac NMDS",
    color = "Humoral response",
    shape = "Vaccination status")

p2_nmds
```

## Compute Bray Curtis for 1-dose
```{r}
bray1 <- distance(ps1, method = "bray")
ord_bray1 <- ordinate(ps1, "NMDS", distance = bray1)
p_bray1 <- plot_ordination(ps1, ord_bray1, color = "Response") +
  stat_ellipse(aes(group = Response),
               type = "t",      
               linetype = 2) +  
  theme_bw()

p_bray1


```

## Compute Bray Curtis for 4-dose
```{r}
bray2 <- distance(ps2, method = "bray")
ord_bray2 <- ordinate(ps2, "NMDS", distance = bray2)
p_bray2 <- plot_ordination(ps2, ord_bray2, color = "Response") +
  stat_ellipse(aes(group = Response),
               type = "t",      
               linetype = 2) +  
  theme_bw()

p_bray2
```

## Perform pairwise PERMANOVA on weighted unifrac (for both 1 and 4 dose)
```{r PERMANOVA}
unifrac_weighted <- distance(ps, method = "unifrac", weighted = TRUE)

meta <- as.data.frame(as(sample_data(ps), "data.frame"))
meta$Vaccination.Status <- factor(meta$Vaccination.Status)
meta$Response <- factor(meta$Response)

dist_mat <- as.matrix(unifrac_weighted)

pairwise_perm <- list()

for (resp in levels(meta$Response)) {
  idx <- which(meta$Response == resp)
  if (length(idx) < 2) next
  if (length(unique(meta$Vaccination.Status[idx])) < 2) next
  
  sub_dist <- as.dist(dist_mat[idx, idx])
  sub_meta <- as.data.frame(meta[idx, , drop = FALSE])
  
  pairwise_perm[[resp]] <- adonis2(
    sub_dist ~ Vaccination.Status,
    data = sub_meta,
    permutations = 999
  )
}

pairwise_perm

```

## Perform pairwise PERMANOVA on weighted unifrac(1-dose)
```{r PERMANOVA for dose 1}

unifrac_weighted_d1 <- distance(ps1, method = "unifrac", weighted = TRUE)

meta_d1 <- as.data.frame(as(sample_data(ps1), "data.frame"))
meta_d1$Response <- factor(meta_d1$Response)


all(rownames(meta_d1) == rownames(as.matrix(unifrac_weighted_d1)))


dist_mat1 <- as.matrix(unifrac_weighted_d1)


lvls1 <- levels(meta_d1$Response)
combs1 <- combn(lvls1, 2, simplify = FALSE)

pw_results1 <- lapply(combs1, function(pair) {
  sub_meta1 <- meta_d1[meta_d1$Response %in% pair, , drop = FALSE]
  sub_dist1 <- as.dist(dist_mat1[rownames(sub_meta1), rownames(sub_meta1)])
  perm1 <- adonis2(sub_dist1 ~ Response,
                  data = sub_meta1,
                  permutations = 999)
  
  data.frame(
    Group1  = pair[1],
    Group2  = pair[2],
    R2      = perm1$R2[1],
    F_value = perm1$F[1],
    p_value = perm1$`Pr(>F)`[1]
  )
})

pw_results1 <- bind_rows(pw_results1)

pw_results1$p_adj <- p.adjust(pw_results1$p_value, method = "BH")

pw_results1
```
## Perform pairwise PERMANOVA on weighted unifrac (4-dose)
```{r PERMANOVA for 4 dose}

unifrac_weighted_d2 <- distance(ps2, method = "unifrac", weighted = TRUE)

meta_d2 <- as.data.frame(as(sample_data(ps2), "data.frame"))
meta_d2$Response <- factor(meta_d2$Response)


all(rownames(meta_d2) == rownames(as.matrix(unifrac_weighted_d2)))
`

dist_mat2 <- as.matrix(unifrac_weighted_d2)


lvls2 <- levels(meta_d2$Response)
combs2 <- combn(lvls2, 2, simplify = FALSE)

pw_results2 <- lapply(combs2, function(pair) {
  sub_meta2 <- meta_d2[meta_d2$Response %in% pair, , drop = FALSE]
  sub_dist2 <- as.dist(dist_mat2[rownames(sub_meta2), rownames(sub_meta2)])
  perm2 <- adonis2(sub_dist2 ~ Response,
                  data = sub_meta2,
                  permutations = 999)
  
  data.frame(
    Group1  = pair[1],
    Group2  = pair[2],
    R2      = perm2$R2[1],
    F_value = perm2$F[1],
    p_value = perm2$`Pr(>F)`[1]
  )
})

pw_results2 <- bind_rows(pw_results2)

pw_results2$p_adj <- p.adjust(pw_results2$p_value, method = "BH")

pw_results2
```

## Taxa Bar Plot 
```{r}
ps_rel <- transform_sample_counts(ps, function(x) x / sum(x))

taxa <- plot_bar(ps_rel, x = "Response", fill = "Family") +
  geom_bar(stat = "identity") +
  facet_wrap(~ Vaccination.Status) +
  theme_classic() +
  labs(
    x = "Humoral response category",
    y = "Relative abundance"
  )

taxa
```

